# Generated by Django 6.0 on 2026-06-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_secretmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmessage',
            name='duration',
            field=models.IntegerField(default=10),
        ),
    ]
